Make GDAL v3.8.1 and 'use-conda' default options
Migrate to latest GDAL v3.8.1. This requires git "core.longpaths" to be
enabled before "Clone GDAL sources" step (otherwise it fails with
"Filename too long").

Make 'use-conda' enabled by default. This is to make the default
parameters under Windows independent from GDAL version in
https://www.gisinternals.com/sdk.php.

Update README.md to document the use NuGet packages, which allows to
avoid huge build delays, esp. under Windows with 'use-conda'.

Under macOS with "use-conda=true", always install "unixodbc" as a
workaround for "libiconv" incompatibility issue:
  ImportError: dlopen(...): Symbol not found: (_iconv)

The above still doesn't work with python 3.7, thus this scenario is
excluded in "validate.yml".